### ISSUE TITLE
Stuck at "Retrieving profile"

### ISSUE THREAD

**Issue by marco-c** [bgirard/Gecko-Profiler-Addon#101]
I see two `unreachable code after return statement` errors and a `TypeError: types is undefined` which comes from:
```JavaScript
function inflateSchemaProfileThreads(profile) {
  function maybeTableEntry(table, index) {
    return index == undefined ? undefined : table[index];
  }

  function inflateOptimizations(optimizations, stringTable) {
    if (optimizations == undefined) {
      return undefined;
    }

    let types = optimizations.types;
    let inflatedTypes = new Array(types.length);
```

I'm using Firefox Nightly on Linux.

**Comment by juj** [comment]
I can reproduce - in current Firefox Nightly on Mac OS X 10.10.2, all captures hang at "Retrieving profile" which blocks examining the profiles.

Examining older local profiles that I had captured a long time ago did work correctly.

**Comment by juj** [comment]
In current Firefox stable 41 profiling did work and the code did get past the "Retrieving profile" and the profile is examinable, however the URL address bar shows URL http://people.mozilla.org/~bgirard/cleopatra/#uploadProfileFirst! , and the top-left panel which should receive list items of the captured profiles does not get an entry, but the panel is empty.

**Comment by juj** [comment]
Trying again today on Firefox 41 stable, I am getting an error alert() dialog with the title "Symbolication Failed" and message

Symbolication request to http://symbolapi.mozilla.org/gecko-profiler/ failed with error code HTTP 503
Please try again later.

@bgirard : do you know if something is off with the servers?

**Comment by bgirard** [comment]
Vladan brought down the server for maintenance. It should be back up eventually.

**Comment by bgirard** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1209779. No need to track this here, closing.
