### ISSUE TITLE
Error: "Unable to connect to the Gecko profiler add-on within five seconds."

### ISSUE THREAD

**Issue by stephendonner** [bgirard/Gecko-Profiler-Addon#115]
Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

I'm using Gecko Profile 0.8, from today, May 9th.

Invoking a profile capture, I just got:
![unable-connect-gecko-profiler-error](https://cloud.githubusercontent.com/assets/387249/25867099/6b0c7f7a-34ad-11e7-881b-9286764f50ce.png)

```"Couldn't retrieve the profile from the gecko profiler addon."
Error was: 'Error: Unable to connect to the Gecko profiler add-on within five seconds.'. The full stack has been written to the Web Console.
```

Error: Unable to connect to the Gecko profiler add-on within five seconds.
Stack trace:
e/</<@https://perf-html.io/9170dacdedc70ab6d307.bundle.js:30:6819
9170dacdedc70ab6d307.bundle.js:33:6467
Unhandled promise rejection Error: Unable to connect to the Gecko profiler add-on within five seconds.
Stack trace:
e/</<@https://perf-html.io/9170dacdedc70ab6d307.bundle.js:30:6819
9170dacdedc70ab6d307.bundle.js:35:46
Successfully compiled asm.js code (loaded from cache in 9169ms)
zee-worker.js

**Comment by bgirard** [comment]
This is no longer the primary fork. You might want to report that here:
https://github.com/devtools-html/Gecko-Profiler-Addon

**Comment by stephendonner** [comment]
Thanks, @bgirard - closing (and this is fine, now that the timeout has been bumped for a little while).
