### ISSUE TITLE
Addon's icon is almost impossible to see on Firefox Nightly using the dark theme

### ISSUE THREAD

**Issue by clement-lefevre** [bgirard/Gecko-Profiler-Addon#116]
As you can see on the joined screenshot, profiler's icon is almost impossible to see on the dark theme using Firefox Nightly.

![capture d ecran 2017-11-07 a 17 56 57](https://user-images.githubusercontent.com/1701721/32507370-817145d8-c3e7-11e7-846d-e7db068d51b5.png)

**Comment by bgirard** [comment]
The main fork is now at:
https://github.com/devtools-html/perf.html

**Comment by clement-lefevre** [comment]
Oh, I thought the repository under your link was for the website/server part and that this repository was just about the addon, doing the interface to the browser?
If that's not the case, I'll just reopen it there then.

Should this issue be closed?

**Comment by julienw** [comment]
The addon indeed lives at its own repository, but it's at https://github.com/devtools-html/Gecko-Profiler-Addon :)

You can close this bug, following up in https://github.com/devtools-html/Gecko-Profiler-Addon/issues/88

**Comment by clement-lefevre** [comment]
Per the above comment, closing this issue then.
