### ISSUE TITLE
Fennec profiling looking in path that would require rooted Android

### ISSUE THREAD

**Issue by garvankeeley** [bgirard/Gecko-Profiler-Addon#83]
I get this message:
Couldn't find apk /data/app/org.mozilla.fennec-NUM.apk

That path is accessible only on a rooted device.

**Comment by bgirard** [comment]
It should be looking at /data/app/org.mozilla.fennec/org.mozilla.fennec-NUM.apk or something similar instead. You can't list the directory but you can access it directly if its the right URL.

The profiler is design to support non rooted Android devices.

**Comment by garvankeeley** [comment]
Thanks, good to know I don't need rooting, I didn't know exact paths could be used without rooting -also good to know.

This output suggests a different path (I am using aurora):
`$ adb shell pm path org.mozilla.fennec_aurora`
`package:/data/app/org.mozilla.fennec_aurora-1/base.apk`

**Comment by bgirard** [comment]
Yea, it's liked rotted and needs to be updated. I'm looking at b2g blockers so I don't have time to look into this ATM sadly :( Sorry

**Comment by garvankeeley** [comment]
No prob, thanks for the info!

**Comment by mstange** [comment]
I'm looking into this at the moment.
